//! The mic effect chain: ordered list of effects + filter-chain config emission.

use std::fmt::Write;

use serde::{Deserialize, Serialize};

use crate::effects::{descriptors_for, EffectInstance, EffectKind};

/// Name of the virtual `Audio/Source` node apps capture from after
/// processing. Stable: this is what the user picks in OBS/Discord.
pub const PROCESSED_SOURCE_NAME: &str = "ut-mic-processed";

/// Name of the passive `Audio/Sink` end of the filter chain — apps
/// don't see this; the daemon links the Wave XLR mic into it.
pub const PROCESSED_SINK_NAME: &str = "ut-mic-processed-input";

/// Ordered effect chain (signal flow left-to-right).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MicChain {
    pub effects: Vec<EffectInstance>,
    /// Last-applied preset name, if any. `None` means custom (user
    /// has tweaked individual params away from any saved preset).
    pub preset: Option<String>,
}

impl Default for MicChain {
    fn default() -> Self {
        Self {
            effects: EffectKind::all()
                .iter()
                .copied()
                .map(EffectInstance::default_for)
                .collect(),
            preset: Some("Off".to_string()),
        }
    }
}

impl MicChain {
    /// Look up a mutable reference to one effect by kind.
    #[must_use]
    pub fn effect_mut(&mut self, kind: EffectKind) -> Option<&mut EffectInstance> {
        self.effects.iter_mut().find(|e| e.kind == kind)
    }

    /// Look up an effect by kind.
    #[must_use]
    pub fn effect(&self, kind: EffectKind) -> Option<&EffectInstance> {
        self.effects.iter().find(|e| e.kind == kind)
    }

    /// Emit a `pipewire-module-filter-chain` properties block. The
    /// daemon writes the result to a config file and loads it via
    /// `pw-cli load-module libpipewire-module-filter-chain
    /// args=…`.
    ///
    /// The chain is fixed at build time (4 mono effects in series);
    /// only the parameter values vary per instance, so this output is
    /// deterministic given the same `MicChain`.
    #[must_use]
    pub fn to_pipewire_config(&self) -> String {
        let mut s = String::with_capacity(2048);
        s.push_str("{\n");
        let _ = writeln!(s, "  node.name        = \"{PROCESSED_SOURCE_NAME}\"");
        let _ = writeln!(s, "  node.description = \"Undertone Processed Mic\"");
        let _ = writeln!(s, "  media.name       = \"Undertone Processed Mic\"");
        s.push_str("  filter.graph = {\n    nodes = [\n");

        for (idx, inst) in self.effects.iter().enumerate() {
            emit_node(&mut s, inst);
            if idx + 1 < self.effects.len() {
                s.push('\n');
            }
        }

        s.push_str("    ]\n    links = [\n");
        for window in self.effects.windows(2) {
            let from = window[0].kind.node_id();
            let to = window[1].kind.node_id();
            let _ = writeln!(s, "      {{ output = \"{from}:out\" input = \"{to}:in\" }}");
        }
        s.push_str("    ]\n");

        let first = self.effects.first().map_or("", |e| e.kind.node_id());
        let last = self.effects.last().map_or("", |e| e.kind.node_id());
        let _ = writeln!(s, "    inputs  = [ \"{first}:in\" ]");
        let _ = writeln!(s, "    outputs = [ \"{last}:out\" ]");

        s.push_str("  }\n");
        let _ = writeln!(s, "  capture.props = {{ node.name = \"{PROCESSED_SINK_NAME}\" node.passive = true }}");
        let _ = writeln!(s, "  playback.props = {{ node.name = \"{PROCESSED_SOURCE_NAME}\" media.class = \"Audio/Source\" }}");
        s.push_str("}\n");
        s
    }

    /// Wrap [`Self::to_pipewire_config`] in the `context.modules`
    /// envelope expected by `~/.config/pipewire/filter-chain.conf.d/`
    /// drop-ins. The result is what gets written to disk.
    #[must_use]
    pub fn to_pipewire_config_drop_in(&self) -> String {
        let inner = self.to_pipewire_config();
        format!(
            "# Generated by undertone-daemon. Do not edit by hand;\n\
             # changes survive only until the daemon rewrites this file.\n\
             context.modules = [\n  {{ name = libpipewire-module-filter-chain\n    args = {inner}  }}\n]\n"
        )
    }

    /// Snapshot suitable for serialization to the IPC client.
    /// Includes the static descriptor table so the UI can render
    /// generic sliders without a separate query.
    #[must_use]
    pub fn snapshot(&self) -> MicChainSnapshot {
        let effects = self
            .effects
            .iter()
            .map(|inst| EffectSnapshot {
                kind: inst.kind,
                bypassed: inst.bypassed,
                params: inst.params.clone(),
                descriptors: descriptors_for(inst.kind)
                    .iter()
                    .map(|d| OwnedParamDescriptor {
                        name: d.name.to_string(),
                        label: d.label.to_string(),
                        min: d.min,
                        max: d.max,
                        default: d.default,
                        step: d.step,
                        unit: d.unit.to_string(),
                    })
                    .collect(),
            })
            .collect();
        MicChainSnapshot {
            effects,
            preset: self.preset.clone(),
        }
    }
}

fn emit_node(out: &mut String, inst: &EffectInstance) {
    let id = inst.kind.node_id();
    match inst.kind {
        EffectKind::NoiseSuppression => {
            // LADSPA RNNoise. Effective bypass: clamp VAD threshold
            // to 0 so the gate is always open.
            let vad = effective_vad(inst);
            let _ = writeln!(
                out,
                "      {{ type = ladspa name = {id} plugin = \"/usr/lib/ladspa/librnnoise_ladspa.so\" label = \"noise_suppressor_mono\" control = {{ \"VAD Threshold (%)\" = {vad} }} }}"
            );
        }
        EffectKind::Gate => emit_lsp(out, id, "http://lsp-plug.in/plugins/lv2/gate_mono", inst),
        EffectKind::Compressor => emit_lsp(out, id, "http://lsp-plug.in/plugins/lv2/compressor_mono", inst),
        EffectKind::Equalizer => emit_lsp(out, id, "http://lsp-plug.in/plugins/lv2/para_equalizer_x16_mono", inst),
    }
}

fn emit_lsp(out: &mut String, id: &str, uri: &str, inst: &EffectInstance) {
    let _ = write!(out, "      {{ type = lv2 name = {id} plugin = \"{uri}\" control = {{ ");
    for (k, v) in &inst.params {
        let _ = write!(out, "\"{k}\" = {v} ");
    }
    let bp = u8::from(inst.bypassed);
    let _ = writeln!(out, "\"bp\" = {bp} }} }}");
}

fn effective_vad(inst: &EffectInstance) -> f32 {
    if inst.bypassed {
        0.0
    } else {
        inst.params
            .get("VAD Threshold (%)")
            .copied()
            .unwrap_or(50.0)
    }
}

/// Wire-format effect snapshot (owned strings for serde).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EffectSnapshot {
    pub kind: EffectKind,
    pub bypassed: bool,
    pub params: std::collections::BTreeMap<String, f32>,
    pub descriptors: Vec<OwnedParamDescriptor>,
}

/// Owned-string copy of [`ParamDescriptor`] for IPC serialization.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OwnedParamDescriptor {
    pub name: String,
    pub label: String,
    pub min: f32,
    pub max: f32,
    pub default: f32,
    pub step: f32,
    pub unit: String,
}

/// Wire-format chain snapshot — the shape served via `Method::GetState`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MicChainSnapshot {
    pub effects: Vec<EffectSnapshot>,
    pub preset: Option<String>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_chain_has_four_effects_in_signal_order() {
        let chain = MicChain::default();
        let kinds: Vec<_> = chain.effects.iter().map(|e| e.kind).collect();
        assert_eq!(kinds, EffectKind::all());
    }

    #[test]
    fn pipewire_config_includes_all_node_ids() {
        let chain = MicChain::default();
        let cfg = chain.to_pipewire_config();
        for &kind in EffectKind::all() {
            assert!(
                cfg.contains(&format!("name = {}", kind.node_id())),
                "missing node id `{}` in:\n{}",
                kind.node_id(),
                cfg
            );
        }
        assert!(cfg.contains(PROCESSED_SOURCE_NAME));
        assert!(cfg.contains(PROCESSED_SINK_NAME));
    }

    #[test]
    fn pipewire_config_links_chain_left_to_right() {
        let chain = MicChain::default();
        let cfg = chain.to_pipewire_config();
        let pairs = EffectKind::all().windows(2);
        for w in pairs {
            let from = w[0].node_id();
            let to = w[1].node_id();
            let needle = format!("output = \"{from}:out\" input = \"{to}:in\"");
            assert!(cfg.contains(&needle), "missing link: {needle}");
        }
    }

    #[test]
    fn snapshot_round_trips_through_json() {
        let chain = MicChain::default();
        let snap = chain.snapshot();
        let s = serde_json::to_string(&snap).unwrap();
        let back: MicChainSnapshot = serde_json::from_str(&s).unwrap();
        assert_eq!(back.effects.len(), 4);
        assert_eq!(back.preset.as_deref(), Some("Off"));
    }

    #[test]
    fn bypass_collapses_vad_to_zero() {
        let mut chain = MicChain::default();
        let ns = chain.effect_mut(EffectKind::NoiseSuppression).unwrap();
        ns.bypassed = true;
        ns.params.insert("VAD Threshold (%)".into(), 75.0);
        let cfg = chain.to_pipewire_config();
        assert!(cfg.contains("\"VAD Threshold (%)\" = 0"));
    }

    #[test]
    fn bypass_sets_bp_port_for_lsp_plugins() {
        let mut chain = MicChain::default();
        chain.effect_mut(EffectKind::Compressor).unwrap().bypassed = true;
        chain.effect_mut(EffectKind::Gate).unwrap().bypassed = false;
        let cfg = chain.to_pipewire_config();
        // Naive but works: each plugin emits its own line.
        for line in cfg.lines() {
            if line.contains("name = comp ") {
                assert!(line.contains("\"bp\" = 1"), "compressor should be bypassed:\n{line}");
            }
            if line.contains("name = gate ") {
                assert!(line.contains("\"bp\" = 0"), "gate should be active:\n{line}");
            }
        }
    }
}
